### PR TITLE
stream stdout

### LINKED ISSUE #2: Stdout of executed jar not printed in shell
`grill update wurstscript`

just shows

```
Forwarded run arguments: ["update", "wurstscript"]
Java arguments: []
```

And the stdout of the jar only appears once it exits.

### PR DESCRIPTION
**Pull request by Cokemonkey11**
@Frotty please review

Closes #2

### CODE REVIEW

**Comment by Frotty** [comment]
`build failed`
Also wrapper toml thing isn't good idea. We will have multiple executable (wurstscript.exe and grill.exe e.g.) which will be in same folder, which should be added to path (`~/.wurst`), so they can be used from shell.
Right now this wouldn't be possible anymore, which is what I told you in chat :thinking:

**Comment by Cokemonkey11** [comment]
> Also wrapper toml thing isn't good idea. We will have multiple executable (wurstscript.exe and grill.exe e.g.) which will be in same folder, which should be added to path (~/.wurst), so they can be used from shell.
> Right now this wouldn't be possible anymore, which is what I told you in chat

I didn't get that in chat. Can you add another issue?

**Comment by Frotty** [comment]
just remove the change in this PR imo.

**Comment by Cokemonkey11** [comment]
As discussed, this PR as-is does not regress our story for being config-fileless. The new parameter is optional.

Will merge when CI passes.

**Pull request merged**
